### ISSUE TITLE
Using a free-software license

### ISSUE THREAD

**Issue by wfdd** [openpatata/openpatata#17]
GNU Affero appears to be popular among similar projects, I presume on account of the fact that it makes redistribution mandatory for websites using the software. Would anybody have any other suggestions? What do we need to consider?

**Comment by akuckartz** [comment]
1. Be compatible with all relevant intended communities.
2. Do not legally require something which is not decisive for your project or those communities

One question to think about: What happens when a public administration wants to use your software and wants to support Open Source but needs to very closely integrate it with proprietary software it is using internally?

**Comment by wfdd** [comment]
Good points, thanks. 

I'm not sure what use government might find in integrating this software with theirs.  I think permitting proprietary use of openpatata itself would be somewhat orthogonal to the spirit of our cause.  When I finally get around to implementing an API, I'll consider creating a supporting library licensed under MIT or similar.

**Comment by akuckartz** [comment]
What was the resolution of this issue?
